# Generated by Django 6.0.3 on 2026-03-14 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='FinanceTransaction',
        ),
    ]
