# Generated by Django 6.0.3 on 2026-03-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_transaction_financetransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financetransaction',
            name='type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=10),
        ),
    ]
